#theme = "space-villain"
theme = "native"

[icons]
name = "awesome"
[icons.overrides]
music = "  "

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"
